# User Story: I want the chatbot to recommend support groups to both inform me about the support available and also to help me connect with people who face similar problems.

# Chain 1
# Goal: Identify user’s preferences for a support group
# Implementation: This chain retrieves relevant data from the user input and all relevant information from the database. Creating a Pydantic model instance containing all information. At the end, the chain returns the information in a string format.


# Chain 2
# Goal: Identify the best support group
# Implementation: This chain processes the user preferences generated by the previous chain, queries the database for the most relevant entries, and retrieves the best matches.


# Chain 3
# Goal: Output the best support group
# Implementation: This chain receives both inputs (user input and best support group match) and generates a final output using a prompt template.
