# User Story: I want Squeak and Speak to use details about my mental health needs, preferences, and location so that I can receive a personalized recommendation for a healthcare professional who matches my needs and preferences.

# Chain 1
# Goal: Identify user’s preferences for a therapist
# Implementation:  This chain retrieves relevant data from the user input and all relevant information from the database. Creating a Pydantic model instance containing all information. At the end, the chain returns the information in a string format.



# Chain 2
# Goal: Identify the best therapist
# Implementation: This chain processes the user preferences generated by the previous chain, queries the database for the most relevant entries, and retrieves the best matches.



# Chain 3
# Goal: Output the best therapist
# Implementation: This chain receives both inputs (user input and best therapist match) and generates a final output using a prompt template.
